import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "../components/navigation/footer";
import Header from "@/components/navigation/header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });
<link rel="icon" href="/favicon.ico" sizes="any" />;

export const metadata = {
  title: "MonetaMind 💗",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.className}`}>
          <Header />
          <main className="min-h-screen">{children}</main>
          <Toaster richColors />
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
